ElectronicMedicalRecords/Models/SinhHoaMau.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectronicMedicalRecords.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SinhHoaMau
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SinhHoaMau()
        {
            this.Detail_SinhHoaMau = new HashSet<Detail_SinhHoaMau>();
        }
    
        public int ID { get; set; }
        public bool ChiDinh { get; set; }
        public string NameTest { get; set; }
        public string CSBT { get; set; }
        public int Price { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detail_SinhHoaMau> Detail_SinhHoaMau { get; set; }
    }
}

ElectronicMedicalRecords/Areas/Admin/Controllers/SinhHoaMausController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ElectronicMedicalRecords.Models;

namespace ElectronicMedicalRecords.Areas.Admin.Controllers
{
    [Authorize(Roles = "Bác Sĩ,Giám Đốc,QTV,Kỹ Thuật Viên,Y tá/Điều dưỡng,Thu Ngân")]
    public class SinhHoaMausController : Controller
    {
        private CP24Team08Entities db = new CP24Team08Entities();

        // GET: Admin/SinhHoaMaus
        public ActionResult Index()
        {
            return View(db.SinhHoaMaus.ToList());
        }

        public ActionResult GetData()
        {
            db.Configuration.ProxyCreationEnabled = false;
            var sinhHoaMaus = db.SinhHoaMaus.ToList();
            return Json(new { data = sinhHoaMaus }, JsonRequestBehavior.AllowGet);
        }
        // GET: Admin/SinhHoaMaus/CreateOldPatient
        public ActionResult CreateOldPatient(MultiplesModel multiplesModel)
        {
            multiplesModel.SinhHoaMau = db.SinhHoaMaus.ToList();
            return PartialView("_CreateOldPatient", multiplesModel);
        }

        // GET: Admin/SinhHoaMaus/Create
        public ActionResult Create()
        {
            MultiplesModel multiplesModel = new MultiplesModel();
            multiplesModel.SinhHoaMau = db.SinhHoaMaus.ToList();
            return PartialView("_Create", multiplesModel);
        }

        // GET: Admin/SinhHoaMaus/Edit/5
        public ActionResult Edit(int id)
        {
            SinhHoaMau sinhHoaMau = db.SinhHoaMaus.Find(id);
            if (sinhHoaMau == null)
            {
                return HttpNotFound();
            }
            var SinhHoaMau = new { sinhHoaMau.ID, sinhHoaMau.NameTest, sinhHoaMau.Price, sinhHoaMau.CSBT, sinhHoaMau.ChiDinh };
            return Json(new { data = SinhHoaMau }, JsonRequestBehavior.AllowGet);
        }

        // POST: Admin/SinhHoaMaus/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken, ValidateInput(false)]
        public ActionResult Edit(SinhHoaMau sinhHoaMau)
        {
            if (ModelState.IsValid)
            {
                db.Entry(sinhHoaMau).State = EntityState.Modified;
                db.SaveChanges();
                return Json(new { success = true });
            }
            return Json(new { success = false, responseText = "Không thể cập nhật giá" });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ElectronicMedicalRecords/Areas/Admin/Views/SinhHoaMaus/Index.cshtml
@model IEnumerable<ElectronicMedicalRecords.Models.SinhHoaMau>

@{
    ViewBag.Title = "Index";
}
@using (Html.BeginForm(null, null, FormMethod.Post, new { id = "__AjaxAntiForgeryForm" }))
{
    @Html.AntiForgeryToken()
}
<header class="mb-3">
    <a href="#" class="burger-btn d-block d-xl-none">
        <i class="bi bi-justify fs-3"></i>
    </a>
</header>
<div class="page-heading">
    <div class="page-title">
        <div class="row">
            <div class="col-12 col-md-6 order-md-1 order-last pdlLeft">
                <h3>Quản Lý Sinh Hóa Máu</h3>
                <p class="text-subtitle text-muted">Bạn có thể xem danh sách sinh hóa máu tại đây</p>
            </div>
            <div class="col-12 col-md-6 order-md-2 order-first abs-t-r">
                <nav aria-label="breadcrumb" class="breadcrumb-header float-start float-lg-end">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="@Url.Action("Index", "SinhHoaMaus")">Danh sách</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Sinh Hóa Máu</li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>
    <section class="section">
        <div class="card">
            <div class="card-body">
                <table class="table table-striped" id="tableSinhHoaMau" style="width:100%">
                    <thead>
                        <tr>
                            <th>Tên</th>
                            <th>CSBT</th>
                            <th>Giá</th>
                            @if (User.IsInRole("Giám Đốc") || User.IsInRole("QTV"))
                            {
                                <th style="width:80px">Chức Năng</th>
                            }
                        </tr>
                    </thead>
                    <tbody></tbody>
                </table>
            </div>
        </div>
    </section>
</div>

<!-- Update Basic Modal -->
<div class="modal fade text-left" id="Updatesinhhoamau" tabindex="-1" role="dialog"
     aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-scrollable modal-700" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="myModalLabel">Cập nhật giá xét nghiệm</h5>
                <button type="button" class="close rounded-pill"
                        data-bs-dismiss="modal" aria-label="Close">
                    <i data-feather="x"></i>
                </button>
            </div>
            <div class="modal-body">
                <form id="form-updateSinhHoaMau" class="form form-horizontal">
                    <div class="form-body">
                        <div class="row">
                            <input value="" type="text" name="NameTest" id="sinhhoamauNameTest" hidden />
                            <input value="" type="checkbox" name="ChiDinh" id="sinhhoamauChiDinh" hidden />
                            <input value="" type="number" name="ID" id="sinhhoamauID" hidden />
                            <input value="" type="text" name="CSBT" id="sinhhoamauCSBT" hidden />
                            <div class="col-md-4">
                                <label>Giá</label>
                            </div>
                            <div class="col-md-8">
                                <div class="form-group has-icon-left">
                                    <div class="position-relative">
                                        <input name="Price" type="number" class="form-control"
                                               placeholder="Giá" id="sinhhoamauPrice" required min="0">
                                        <div class="form-control-icon">
                                            <i class="fas fa-money-bill-wave"></i>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn" data-bs-dismiss="modal">
                                <i class="bx bx-x d-block d-sm-none"></i>
                                <span class="d-none d-sm-block">Hủy</span>
                            </button>
                            <button type="submit" id="updateSinhHoaMau" class="btn btn-primary ml-1">
                                <i class="bx bx-check d-block d-sm-none"></i>
                                <span class="d-none d-sm-block">Cập Nhật</span>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@section scripts{
    <script type="text/javascript">
        $(document).ready(function () {
            var RoleCheck = @(User.IsInRole("Giám Đốc") || User.IsInRole("QTV") ? "true" : "false");
            $('#tableSinhHoaMau').DataTable({
                "ajax": {
                    "url": "@Url.Action("GetData", "SinhHoaMaus")",
                    "type": "GET",
                    "datatype": "json"
                },
                "columns": [
                    {
                        "data": "NameTest",
                    },
                    {
                        "data": "CSBT",
                    },
                    {
                        "data": "Price",
                    },
                    {
                        "className": "w45",
                        "data": null,
                        "render": function (data, type, row) {
                            var button = "<button class='btn btn-primary btnHover edit' onclick='getSinhHoaMauByID(" + data.ID + ")' data-id='"
                                + data.ID + "'> <i class='fas fa-user-edit'></i> </button>";
                            return button;
                        },
                        "targets": 0,
                        "orderable": false
                    }
                ],
                "language": {
                    "emptyTable": "No data available, please click on <b>Tạo Chẩn Đoán</b> button",
                    "oPaginate": {
                        sNext: '<i class="fa fa-chevron-right"></i>',
                        sPrevious: '<i class="fa fa-chevron-left"></i>',
                    },
                    "info": "Hiển thị _START_/_END_ trên tổng _TOTAL_",
                    "lengthMenu": "Hiển thị _MENU_ xét nghiệm",
                    "search": "Tìm kiếm:",
                },
                "columnDefs": [
                    {
                        "targets": [3], //four column
                        "visible": RoleCheck
                    }
                ]
            })
            updateSinhHoaMau()
        })

        function getSinhHoaMauByID(id) {
            $.ajax({
                url: '@Url.Action("Edit", "SinhHoaMaus")',
                type: 'GET',
                data: { id: id },
                success: function (res) {
                    if (res.data != null) {
                        $('#sinhhoamauPrice').val(res.data.Price);
                        $('#sinhhoamauNameTest').val(res.data.NameTest);
                        $('#sinhhoamauChiDinh').val(res.data.ChiDinh);
                        $('#sinhhoamauCSBT').val(res.data.CSBT);
                        $('#sinhhoamauID').val(res.data.ID);
                    }
                }
            })
            $('#Updatesinhhoamau').modal('show')
        }

        function updateSinhHoaMau() {
            $('#form-updateSinhHoaMau').submit((e) => {
                var dataSinhHoaMau = $('#form-updateSinhHoaMau').serialize();
                var form = $('#__AjaxAntiForgeryForm');
                var token = $('input[name="__RequestVerificationToken"]', form).val();
                var model = {
                    validata: dataSinhHoaMau,
                }
                $.ajax({
                    url: "@Url.Action("Edit", "SinhHoaMaus")",
                    type: "POST",
                    data: model.validata + "&__RequestVerificationToken=" + token,
                    success: (res) => {
                        if (res.success) {
                            $('#Updatesinhhoamau').modal('hide');
                            $(document.body).removeClass('modal-open').attr("style", "none");
                            $('.modal-backdrop').remove();
                            Swal.fire({
                                position: 'center',
                                icon: 'success',
                                title: 'Bạn đã cập nhật thành công',
                                showConfirmButton: false,
                                timer: 1500
                            })
                            $('#tableSinhHoaMau').DataTable().ajax.reload();
                        }
                        else {
                            Toastify({
                                text: res.responseText,
                                className: "info",
                                duration: 1500,
                                style: {
                                    background: "linear-gradient(to right, #00b09b, #96c93d)",
                                }
                            }).showToast();
                        }
                    }
                })
                e.preventDefault();
            })
        }
    </script>
}

ElectronicMedicalRecords/Areas/Admin/Views/SinhHoaMaus/_Create.cshtml
@model ElectronicMedicalRecords.Models.MultiplesModel

<div class="card-header pd-0px">
    <div class="d-flex justify-content-between align-items-center">
        <h6 style="margin: 1rem 0.5rem">
            Số lượng xét nghiệm :
            <span class="countTests">0</span>
        </h6>
        @*<button class="btn btn-primary">Giao Diện In</button>*@
    </div>
    <!-- button trigger for  Vertically Centered modal -->
    <button style="display:none;margin-left:10px" onclick="loadDetailTestsSHM()" id="DetailTestCount" type="button" class="btn btn-outline-primary block"
            data-bs-toggle="modal" data-bs-target="#DetailTestCountSHM">
        Chi Tiết
    </button>
    <div class="d-flex align-items-center" style="margin-left:8px">
        <input class="form-check-input form-check-primary" id="checkAll" type="checkbox" />
        <label style="padding-left:1rem;padding-top:1px" class="form-check-label" for="checkAll">Xét nghiệm tổng</label>
    </div>
    <!-- Vertically Centered modal Modal -->
    <div class="modal fade" id="DetailTestCountSHM" tabindex="-1" role="dialog"
         aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
        <div style="max-width:900px" class="modal-dialog modal-dialog-centered modal-dialog-centered modal-dialog-scrollable"
             role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalCenterTitle">
                        Chỉ định xét nghiệm
                    </h5>
                    <button type="button" class="close" data-bs-dismiss="modal"
                            aria-label="Close">
                        <i data-feather="x"></i>
                    </button>
                </div>
                <div class="modal-body">
                    <table class="table table-striped tableNewChiDinh" id="tableNewSinhHoaMau" style="width: 100%">
                        <thead>
                            <tr>
                                <th>Chỉ Định</th>
                                <th>Tên Xét Nghiệm</th>
                                <th hidden></th>
                                <th>Chỉ Số Bình Thường</th>
                            </tr>
                        </thead>
                        <tbody></tbody>
                    </table>
                </div>
                <div class="modal-footer">
                    <button id="destroytable" type="button" class="btn btn-primary ml-1"
                            data-bs-dismiss="modal">
                        <i class="bx bx-check d-block d-sm-none"></i>
                        <span class="d-none d-sm-block">Tắt</span>
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="card-body">
    <table class="table table-striped tableLoad" id="tableSinhHoaMau" style="width:100%">
        <thead>
            <tr>
                <th hidden></th>
                <th>Chỉ Định</th>
                <th>Tên Xét Nghiệm</th>
                <th>Chỉ Số Cân Bằng</th>
            </tr>
        </thead>
        <tbody>
            @for (int i = 0; i < Model.SinhHoaMau.Count(); i++)
            {
                <tr>
                    <td hidden>
                        <input value="@Model.SinhHoaMau[i].Price" type="number" name="SinhHoaMau[@i].Price" hidden />
                        <input value="@Model.SinhHoaMau[i].ID" type="text" name="SinhHoaMau[@i].ID" hidden />
                    </td>
                    <td>
                        <input type="checkbox" value="false" class="form-check-input form-check-primary updateCountTests" data-id="@Model.SinhHoaMau[i].ID" name="SinhHoaMau[@i].ChiDinh" id="SHM-@Model.SinhHoaMau[i].ID">
                    </td>
                    <td>
                        <input value="@Model.SinhHoaMau[i].NameTest" type="text" name="SinhHoaMau[@i].NameTest" hidden />
                        <label class="form-check-label" for="customColorCheck-@Model.SinhHoaMau[i].ID">@Model.SinhHoaMau[i].NameTest</label>
                    </td>
                    <td>
                        <input value="@Model.SinhHoaMau[i].CSBT" type="text" name="SinhHoaMau[@i].CSBT" hidden />
                        @*@Model.SinhHoaMau[i].CSBT*@
                        @Html.Raw(Model.SinhHoaMau[i].CSBT)
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

ElectronicMedicalRecords/Areas/Admin/Views/SinhHoaMaus/_CreateOldPatient.cshtml
@model ElectronicMedicalRecords.Models.MultiplesModel

<div class="card-header pd-0px">
    <div class="d-flex justify-content-between align-items-center">
        <h6 style="margin: 1rem 0.5rem">
            Số lượng xét nghiệm :
            <span class="countTests">0</span>
        </h6>
        <a class="btn btn-primary" id="PrintSinhHoaMaus">In Chỉ Định Xét Nghiệm Sinh Hóa Máu</a>
    </div>
    <!-- button trigger for  Vertically Centered modal -->
    <button style="display:none;margin-left:10px" onclick="loadDetailTestsSHM()" id="DetailTestCount" type="button" class="btn btn-outline-primary block"
            data-bs-toggle="modal" data-bs-target="#DetailTestCountSHM">
        Chi Tiết
    </button>
    <div class="d-flex align-items-center" style="margin-left:8px">
        <input class="form-check-input form-check-primary" id="checkAll" type="checkbox" />
        <label style="padding-left:1rem;padding-top:1px" class="form-check-label" for="checkAll">Xét nghiệm tổng</label>
    </div>
    <!-- Vertically Centered modal Modal -->
    <div class="modal fade" id="DetailTestCountSHM" tabindex="-1" role="dialog"
         aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
        <div style="max-width:900px" class="modal-dialog modal-dialog-centered modal-dialog-centered modal-dialog-scrollable"
             role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalCenterTitle">
                        Chỉ định xét nghiệm
                    </h5>
                    <button type="button" class="close" data-bs-dismiss="modal"
                            aria-label="Close">
                        <i data-feather="x"></i>
                    </button>
                </div>
                <div class="modal-body">
                    <table class="table table-striped tableNewChiDinh" id="tableNewSinhHoaMau" style="width: 100%">
                        <thead>
                            <tr>
                                <th>Chỉ Định</th>
                                <th>Tên Xét Nghiệm</th>
                                <th>Chỉ Số Bình Thường</th>
                            </tr>
                        </thead>
                        <tbody></tbody>
                    </table>
                </div>
                <div class="modal-footer">
                    <button id="destroytable" type="button" class="btn btn-primary ml-1"
                            data-bs-dismiss="modal">
                        <i class="bx bx-check d-block d-sm-none"></i>
                        <span class="d-none d-sm-block">Tắt</span>
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="card-body">
    <table class="table table-striped tableLoad" id="tableSinhHoaMau" style="width:100%">
        <thead>
            <tr>
                <th hidden></th>
                <th>Chỉ Định</th>
                <th>Tên Xét Nghiệm</th>
                <th>Chỉ Số Cân Bằng</th>
            </tr>
        </thead>
        <tbody>
            @for (int i = 0; i < Model.SinhHoaMau.Count(); i++)
            {
                <tr>
                    <td hidden>
                        <input value="@Model.SinhHoaMau[i].Price" type="number" name="SinhHoaMau[@i].Price" hidden />
                        <input value="@Model.SinhHoaMau[i].ID" type="text" name="SinhHoaMau[@i].ID" hidden />
                    </td>
                    <td>
                        <input type="checkbox" value="false" class="form-check-input form-check-primary updateCountTests" data-id="@Model.SinhHoaMau[i].ID" name="SinhHoaMau[@i].ChiDinh" id="SHM-@Model.SinhHoaMau[i].ID">
                    </td>
                    <td>
                        <input value="@Model.SinhHoaMau[i].NameTest" type="text" name="SinhHoaMau[@i].NameTest" hidden />
                        <label class="form-check-label" for="customColorCheck-@Model.SinhHoaMau[i].ID">@Model.SinhHoaMau[i].NameTest</label>
                    </td>
                    <td>
                        <input value="@Model.SinhHoaMau[i].CSBT" type="text" name="SinhHoaMau[@i].CSBT" hidden />
                        @*@Model.SinhHoaMau[i].CSBT*@
                        @Html.Raw(Model.SinhHoaMau[i].CSBT)
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>